### PR TITLE
fix(conditional-os): Add the correct conditional for os

### LINKED ISSUE #16: mv: cannot stat 'README_to_copy.md': No such file or directory
Creating an app on linux. While the `mv` commands should work, the given file does indeed not exist, when they're being executed.

```
➜ npx gras-react-boilerplate test2
info Initializing project...
info Creating the app at "test2"
info Running on "linux"

success npm init -- done

info Generating files...
mv: cannot stat 'README_to_copy.md': No such file or directory
node:child_process:675
    throw err;
    ^

Error: Command failed: cd test2 && mv README_to_copy.md README.md
mv: cannot stat 'README_to_copy.md': No such file or directory

    at checkExecSyncError (node:child_process:636:11)
    at execSync (node:child_process:672:15)
    at /usr/local/share/.config/yarn/global/node_modules/@dhi-gras/gras-react-boilerplate/bin/index.js:121:7
    at ChildProcess.exithandler (node:child_process:300:7)
    at ChildProcess.emit (node:events:327:20)
    at maybeClose (node:internal/child_process:1048:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(63) [Uint8Array] [
      109, 118,  58,  32,  99,  97, 110, 110, 111, 116,  32,
      115, 116,  97, 116,  32,  39,  82,  69,  65,  68,  77,
       69,  95, 116, 111,  95,  99, 111, 112, 121,  46, 109,
      100,  39,  58,  32,  78, 111,  32, 115, 117,  99, 104,
       32, 102, 105, 108, 101,  32, 111, 114,  32, 100, 105,
      114, 101,  99, 116, 111, 114, 121,  10
    ]
  ],
  pid: 30279,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(63) [Uint8Array] [
    109, 118,  58,  32,  99,  97, 110, 110, 111, 116,  32,
    115, 116,  97, 116,  32,  39,  82,  69,  65,  68,  77,
     69,  95, 116, 111,  95,  99, 111, 112, 121,  46, 109,
    100,  39,  58,  32,  78, 111,  32, 115, 117,  99, 104,
     32, 102, 105, 108, 101,  32, 111, 114,  32, 100, 105,
    114, 101,  99, 116, 111, 114, 121,  10
  ]
}
```

### PR DESCRIPTION
**Pull request by bertearazvan**
While this might not fix `#16` , it's a step forward 👍🏻

### CODE REVIEW

**Comment by rihr** [comment]
I'm still getting the same result as in #16 . Does it fix the issue you mentioned with Windows?

**Comment by bertearazvan** [comment]
When using `yarn link` and then using `dhi-gras-boilerplate test` it works for me to bootstrap the app on my local win10.

**Comment by bertearazvan** [comment]
But to answer the question, no, this PR should not fix that issue, it's only something I noticed when I looked through it.

**Pull request merged**
